### ISSUE TITLE
static LDR image in training set

### ISSUE THREAD

**Issue by Carrotor116** [elliottwu/DeepHDR#12]
Hi, thanks for providing the way of downloading  Kalantari's dataset. 

I find that there are three static LDR images named `ref_i.tif` in each training scene. While I also down dataset from Kalantari's project web, and static LDR images are not provided.

So, are these pictures the original static images for generating the ground truth HDR? Or are them produced from ground truth HDR by apply inverse gamma correction?

**Comment by elliottwu** [comment]
Hi! They are the original static images used to generate the GT HDR. I probably should not have shared those images, but please cite Kalantari's paper if you find them useful :)

**Comment by Carrotor116** [comment]
Thank you. They help others to understand how to make GT HDR :)
