### ISSUE TITLE
raw

### ISSUE THREAD

**Issue by lr2427** [elliottwu/DeepHDR#14]
Hi,
Thanks for your job. I have some questions . The paper describes that the radiometric calibration and gamma correction are needed if the LDR is not in RAW format, however I don't see them in the code. Is the input of the network is in rgb format? Otherwise,  If the input image is raw format, how to use the network? is demosaicking needed to convert RAW to RGB?

**Comment by elliottwu** [comment]
Hi, 
The images in the dataset have been calibrated and gamma corrected. It's some detail that will only become important when recovering actual physical radiance. For perceptually plausible results, radiometric calibration is not necessary. 

Demosiacking is needed. Ultimately, as long as the input preprocessing is consistent for training and testing, whichever input format you use should not really matter too much. If you are just using the trained model for inference, I would recommend feeding rgb images (they will be mapped to HDR domain using [inverse gamma correction](https://github.com/elliottwu/DeepHDR/blob/515f98c2bc15506428db14a95931f5089445706a/model.py#L23)).
