### ISSUE TITLE
why the size of output becomes small when test

### ISSUE THREAD

**Issue by zhLawliet** [elliottwu/DeepHDR#4]
1 when i set the --test_h 682 --test_w 1024
ValueError: Dimension 1 in both shapes must be equal, but are 170 and 171 for 'generator/decoder/concat_1' (op: 'ConcatV2') with input shapes: [1,170,256,128], [1,171,256,128]

**Comment by elliottwu** [comment]
Please set the height/width to multiples of 8, such as 680x1024. This is due to the three downsampling convolutions with stride 2, which will have troubles dealing with sizes indivisible by 8.

**Comment by zhLawliet** [comment]
@elliottwu thanks
