### ISSUE TITLE
difference in display of hdr image

### ISSUE THREAD

**Issue by Carrotor116** [elliottwu/DeepHDR#5]
I run `test.sh` with your pretrained model, but got a different result with yours. The following results are my test result (upside) and yours (downside):

![test_000_001_tonemapped](https://user-images.githubusercontent.com/22851737/58615957-feca2a00-82ee-11e9-9d3b-7ab6c7914881.png)

![result in README.md](https://raw.githubusercontent.com/elliottwu/DeepHDR/master/img/hdr_teaser.jpg)

So what is the `tonemap` function that you use to display the final hdr image ?

**Comment by elliottwu** [comment]
All HDR results were visualized using Photomatix (https://www.hdrsoft.com/), as explained at https://github.com/elliottwu/DeepHDR#tonemapping-post-processing.

**Comment by Carrotor116** [comment]
Thanks, while results of using the parameter of the pre-defined styles (`Detailed` and `Painterly2`) is still different with yours. 

`Detailed` style: 
![detailed](https://user-images.githubusercontent.com/22851737/58621091-350da680-82fb-11e9-902e-110e817c121f.png)

`Painterly2` style: 
![painterly2](https://user-images.githubusercontent.com/22851737/58621085-2e7f2f00-82fb-11e9-9d91-df3fcd24ecfc.png)

Do you adjust  the parameter settings by hand ?

**Comment by elliottwu** [comment]
Yes, we used a specific set of parameters for all images. We have lost track of the parameter configuration, but I believe it should be easy for you find a proper set of parameters.

**Comment by Carrotor116** [comment]
thx :)
