### ISSUE TITLE
i have two question about the code

### ISSUE THREAD

**Issue by GentlemanWally** [elliottwu/DeepHDR#6]
Thank you for your work.
I have two question about the code.
1.In your paper, you have trained data by GPU.But when I run the code which you provide,the GPU is not work.
2.I don`t know how to align my pictures use homography transformation,can you provide to me your code?

**Comment by elliottwu** [comment]
Thanks for your interest. 
1. What was the error? I think the code should be fine. It might be related to your environment configuation. Could you provide more details? 
2. I have lost track of the original code, but we used OpenCV for homography registration. You can find lots of examples online, here is one: https://www.learnopencv.com/image-alignment-feature-based-using-opencv-c-python/.
